version: '3.8'
services:
  web:
    build:
      context: ./
    platform: 'linux/amd64'
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development