import React from 'react';
import { Button, Grid } from '@material-ui/core'

const Policy = () => {

  return (
    // <Paper>
    <div style={{ margin: 100 }}>
      <h2>Policy</h2>
      <Grid container spacing={1} direction="row" >
        <Grid item xs={12} sm={10} style={{ padding: 10 }}>
          <p>PRIVACY  POLICY</p>
          <p>Last updated: October 24,2018</p>
          <p>This Privacy Policy describes the information collected by i69 and its associated applications and websites (we, us or i69), operated by Wing Designs, Inc., how that information may be used, with whom it may be shared, and your choices about such uses and disclosures. We encourage you to read this Privacy Policy carefully when using our mobile applications and websites, (the “Services”) or transacting business with us. By using our Services, you are accepting the practices described in this Privacy Policy.</p>
          <p>If you have any questions about our privacy practices, please refer to the end of this Privacy Policy for information on how to contact us.</p>
          <p>The information we collect</p>
          <p>In General. We may collect Personal Information, including Sensitive Data, and other information. “Personal Information” means individually identifiable information that would allow us to determine the actual identity of, and contact, a specific living person. Sensitive Data includes information, comments or content (e.g. photographs, video, profile, lifestyle) that you optionally provide that may reveal your ethnic origin, nationality, religion and/or sexual orientation. By providing Sensitive Data to us, you consent to the collection, use and disclosure of Sensitive Data as permitted by applicable privacy laws. We may also collect your geolocation information with your consent. We may collect this information through a website, mobile application or other online service. When you provide personal information, the information may be sent to servers located in the United States and other countries around the world.</p>
          <p>Information you provide. We may collect and store any personal information you enter on our website or on a mobile application, or provide to us in some other manner. This includes identifying information, such as your name, address, email address and telephone number, and, if you transact business with us, financial information such as your payment method (valid credit card number, type, expiration date or other financial information). You may also provide us information about your interests and activities, your gender and age, and other demographic information such as your hometown or your username.</p>
          <p>Information from other sources. i69 may obtain both personal and non-personal information about you from other businesses, business partners, contractors and other third parties and add it to our account information or other information we have collected. We may also receive information about our users from third party social platforms, such as Facebook. When you access or use our website or mobile application through such a site you allow us to access or collect information made available by the third party site in accordance with its privacy policy. This information may be available from your profile or account with such site or from cookies placed on your device by the third party platform.</p>
          <p>Information about others. We may collect and store personal information about other people that you provide to us, such as their name, address and email address. If you use our Services to send others (friends, relatives, colleagues, etc.) a product as a gift, we may store your personal information, and the personal information of each such recipient in order to process those requests or facilitate future activities.</p>
          <p>Use of cookies and other technologies to collect information. We use various technologies to collect information from your device and about your activities on our site or application.</p>
          <p>Information collected automatically. We automatically collect information from your browser or device when you visit our website or application. This information could include your IP address, device ID, your browser type and language, access times, the content of any undeleted cookies that your browser previously accepted from us (see “Cookies” below), and the referring website address.</p>
          <p>Cookies and Use of Cookie and Other Data. When you visit our website or application, we may assign your device one or more cookies, to facilitate access to our site and to personalize your online experience. Through the use of a cookie, we also may automatically collect information about your online activity on our site, such as the pages you visit, the time and date of your visits, the links you click, and the searches you conduct on our site. During your visits to other websites or applications where we advertise, we (or third parties) may use certain data collected on our site to show you i69.com advertisements.</p>
          <p>Other Technologies. We may use standard Internet technology, such as web beacons, pixel tags, local storage and other technologies that facilitate personalization to track your use of our Services. We also may use these technologies in advertisements or email messages to determine whether messages have been opened and acted upon. The information we obtain in this manner enables us to customize the services we offer our website or application visitors to deliver targeted advertisements and to measure the overall effectiveness of our online advertising, content, programming or other activities.</p>
          <p>Information collected by third-parties. We may allow service providers, companies, advertising companies, ad networks and other third parties, to display advertisements on our site. These companies may use tracking technologies, such as cookies, to collect information about users who view or interact with their advertisements. We do not provide any non-masked or non-obscured personal information to these third parties.</p>
          <p>How we use the information we collect</p>
          <p>In General. We may use information that we collect about you to:</p>
          <p>deliver our products and services, and manage our business;</p>
          <p>manage your account and provide you with customer support;</p>
          <p>perform research and analysis about your use of, or interest in, our products, services, or content, or products, services or content offered by others;</p>
          <p>communicate with you by email, postal mail, telephone and/or mobile devices about products or services that may be of interest to you either from us, other Wing Designs, inc companies or other third parties;</p>
          <p>develop and display content and advertising tailored to your interests on our site and other sites, including providing our advertisements to you when you visit other sites;</p>
          <p>perform ad tracking and website or mobile application analytics;</p>
          <p>verify your eligibility and deliver prizes in connection with contests and sweepstakes;</p>
          <p>enforce or exercise any rights in our terms and conditions; and</p>
          <p>perform functions as otherwise described to you at the time of collection.</p>
          <p>Financial information. We may use financial information or payment method information to (i) process payment for any purchases, (ii) enroll you in the discount, rebate, and other programs in which you elect to participate, (iii) to protect against or identify possible fraudulent transactions, and (iv) otherwise as needed to manage our business.</p>
          <p>Job applicants. If your personal information is submitted when applying for a position with our company, the information will be used solely in connection with considering and acting upon your application. We may retain your personal information, but only for the purpose of considering your application for current or future available positions. This information, which may include your name and contact information, prior education and experience, and other information you provided to us, may be shared with other Wing Designs, inc companies for the purpose of evaluating your qualifications for the particular position or other available positions, as well as with third-party service providers retained by us to collect, maintain and analyze candidate submissions for job postings.</p>
          <p>Please review “Your choices about collection and use of your information” below.</p>
          <p>In all circumstances, we may perform these functions directly or use a third party vendor to perform these functions on our behalf who will be obligated to use your personal information only to perform services for us. Also, if you access our website, mobile applications or other online services from a third party social platform, such as Facebook, we may share non-personal information with that platform to the extent permitted by your agreement with it and its privacy settings.</p>
          <p>With whom we share your information</p>
          <p>Personal information. We do not share your personal information with others except as indicated in this Privacy Policy or when we inform you and give you an opportunity to opt out of having your personal information shared. We may share information, including personal information, with third parties that perform certain services on our behalf. These services may include fulfilling orders, providing customer service (including through our users who moderate flagged content for the i69 community) and marketing assistance, performing business and sales analysis, ad tracking and analytics, member screenings, supporting our website or application functionality, and supporting contests, sweepstakes, surveys and other features offered through our Services. We may also share your name, contact information and credit card information with our service providers who process credit card payments. These service providers may have access to personal information needed to perform their functions but are not permitted to share or use such information for any other purposes.</p>
          <p>Business partners. When you register or make purchases on our Services or click-through our advertisements offered on third party websites or applications, we may share personal information with the businesses with which we partner to offer you the applicable products, services or any advertisements. When you elect to engage in a particular merchant’s offer or program, you authorize us to provide your email address and other information to that merchant.</p>
          <p>Other Situations. We also may disclose your information, including personal information:</p>
          <p>In response to a subpoena or similar investigative demand, a court order, or a request for cooperation from a law enforcement or other government agency; to establish or exercise our legal rights; to defend against legal claims; or as otherwise required by law. In such cases, we may raise or waive any legal objection or right available to us.</p>
          <p>When we believe disclosure is appropriate in connection with efforts to investigate, prevent, or take other action regarding illegal activity, suspected fraud or other wrongdoing; to protect and defend the rights, property or safety of our company, our users, our employees, or others; to comply with applicable law or cooperate with law enforcement; or to enforce our website terms and conditions or other agreements or policies.</p>
          <p>In connection with a substantial corporate transaction, such as the sale of our business, a divestiture, merger, consolidation, or asset sale, or in the unlikely event of bankruptcy.</p>
          <p>Aggregated and/or non-personal-information. We may share non-personal information we collect under any of the above circumstances. We may also share it with Wing Designs, Inc companies and third parties to develop and deliver targeted advertising on our Services and on websites or applications of third parties, and to analyze and report on advertising you see. We may combine non-personal information we collect with additional non-personal information collected from other sources. We also may share aggregated, non-personal information, or personal information in hashed, non-human readable form, with third parties, including advisors, writers, researchers, partners, advertisers and investors for the purpose of conducting general business analysis, advertising, marketing, or other business purposes. For example, we may engage a data provider who may collect web log data from you (including IP address and information about your browser or operating system), or place or recognize a unique cookie on your browser to enable you to receive customized ads or content. The cookies may reflect de-identified demographic or other data linked to data you voluntarily have submitted to us (such as your email address), that we may share with a data provider solely in hashed, non-human readable form. We may also share your geolocation information in de-identified form with Wing Designs, inc companies and third parties for the above purposes. To opt out of the sharing of your geolocation information, please discontinue use of your i69 application.</p>
          <p>Onward transfer and consent to international processing</p>
          <p>
            We are a growing corporation with users and operations in multiple countries, including the European Union. We have developed data practices designed to assure information is appropriately protected but we cannot always know where personal information may be accessed or processed. While our primary data centers are in the United States, we may transfer personal information or other information to our offices outside of the United States. In addition, we may employ other companies and individuals to perform functions on our behalf. If we disclose personal information to a third party or to our employees outside of the United States, we will seek assurances that any information we may provide to them is safeguarded adequately and in accordance with this Privacy Policy and the requirements of applicable privacy laws.</p>
          <p>If you are visiting from the European Union or other regions with laws governing data collection and use, please note that you are agreeing to the transfer of your personal data, including sensitive data, by i69 from your region to countries which do not have data protection laws that provide the same level of protection that exists in countries in the European Economic Area, including the United States. By providing your personal information, you consent to any transfer and processing in accordance with this Policy.</p>
          <p>Do Not Track browser signals</p>
          <p>At this time, our website does not recognize automated browser signals regarding tracking mechanisms, which may include “do not track” instructions. However, you may be able to change your privacy preferences regarding the use of cookies and similar technologies through your browser, as described above.</p>
          <p>Third-party websites</p>
          <p>There are a number of places on our Services where you may click on a link to access other websites that do not operate under this Privacy Policy. For example, if you click on an advertisement on our Services, you may be taken to a website that we do not control. These third-party websites may independently solicit and collect information, including personal information, from you and, in some instances, provide us with information about your activities on those websites. We recommend that you consult the privacy statements of all third-party websites you visit by clicking on the “privacy” link typically located at the bottom of the webpage you are visiting.</p>
          <p>How you can access and correct your information</p>
          <p>If you have an account with us, you have the ability to review and update your personal information by logging into your account and clicking on Settings. Applicable privacy laws may allow any individual the right to access and/or request the correction of errors or omissions in his or her personal information that is in our custody or under our control</p>
          <p>Data retention</p>
          <p>If you have an online account with us, you may delete or disable your account at any time by visiting the “Settings” page for your account. If you delete or disable your account, we will retain certain data for analytical purposes and recordkeeping integrity, as well as to prevent fraud, collect any fees owed, enforce our terms and conditions, take actions we deem necessary to protect the integrity of our Services or our users, or take other actions otherwise permitted by law. In addition, if certain information has already been provided to third parties as described in this Privacy Policy, retention of that information will be subject to those third parties’ policies.</p>
          <p>Your choices about collection and use of your information</p>
          <p>
            You can choose not to provide us with certain information, but that may result in you being unable to use certain features of our Services because such information may be required in order for you to register as a member; purchase products or services; participate in a contest, promotion, survey, or sweepstakes; ask a question; or initiate other transactions on our Services.</p>
          <p>When you register on our Services, you consent to receive email messages from us. You may be given the opportunity, in any commercial email that we send to you, to opt out of receiving such messages in the future. We request a reasonable time to process an opt-out request. We may send you other types of transactional and relationship email communications, such as service announcements, administrative notices, and surveys, without offering you the opportunity to opt out of receiving them. Please note that changing information in your account, or otherwise opting out of receipt of promotional email communications, will only affect future activities or communications from us. If we have already provided your information to a third party (such as a service provider) before you have changed your preferences or updated your information, you may have to change you preferences directly with that third party.</p>
          <p>Our applications may also deliver notifications to your phone or mobile device. You can disable these notifications in your device’s settings in your account under “Settings” or by deleting the relevant application.</p>
          <p>How we protect your personal information</p>
          <p>
            We take appropriate security measures (including physical, electronic and procedural measures) to help safeguard your personal information from unauthorized access and disclosure. We want you to feel confident using our Services to transact business. However, no system can be completely secure. Therefore, although we take steps to secure your information, we do not promise, and you should not expect, that your personal information, searches, or other communications will always remain secure. Users should also take care with how they handle and disclose their personal information and should avoid sending personal information through insecure email. Please refer to the Federal Trade Commission’s website for information about how to protect yourself against identity theft.</p>
          <p>You agree that we may communicate with you electronically regarding security, privacy, and administrative issues, such as security breaches. We may post a notice on our Service if a security breach occurs. We may also send an email to you at the email address you have provided to us.</p>
          <p>Information you provide about yourself while using our service</p>
          <p>
            We provide areas on our Services where you can post information about yourself and others and communicate with others or upload content such as photographs. Such postings are governed by our Terms & Conditions. In addition, such postings may appear on other websites or when searches are executed on the subject of your posting. Also, whenever you voluntarily disclose personal information on publicly-viewable web pages, that information will be publicly available and can be collected and used by others. For example, if you post your email address, you may receive unsolicited messages. We cannot control who reads your posting or what other users may do with the information you voluntarily post, so we encourage you to exercise discretion and caution with respect to your personal information.</p>
          <p>No Rights of Third Parties</p>
          <p>
            This Privacy Policy does not create rights enforceable by third parties or require disclosure of any personal information relating to users of the Services.</p>
          <p>Changes to this Privacy Policy</p>
          <p>We will occasionally update this Privacy Policy. When we post changes to this Privacy Policy, we will revise the “last updated” date at the top of this Privacy Policy. We recommend that you check our website from time to time to inform yourself of any changes in this Privacy Policy or any of our other policies.</p>

        </Grid>
        <Grid item xs={12} sm={2}>
          <Button variant="contained" style={{ margin: 50 }} color="secondary" href="https://play.google.com/store/apps/details?id=com.i69app.i69app&pli=1" target="_blank">
            Download
          </Button>
        </Grid>
      </Grid>
    </div>
  );
}

export default Policy;